version: 0.0
os: linux
files:
  - source: src/index.html
    destination: /usr/share/nginx/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  # ApplicationStart:
  #   - location: scripts/restart_server.sh
  #     timeout: 300
  #     runas: root